# Generated by Django 2.1.1 on 2018-09-16 04:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_unique_uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('cab_license_plate_number', models.CharField(max_length=15)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='cab_category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_model_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('category', models.CharField(max_length=200)),
                ('cab_description', models.CharField(max_length=500)),
                ('rate_card', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CabBooking',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cab_booking_id', models.CharField(default='UlFQ5eIu4bSOzKe', max_length=15)),
                ('pickup_date', models.DateField(max_length=20, verbose_name='Date')),
                ('pickup_time_start', models.DateTimeField(max_length=32)),
                ('pickup_lat', models.FloatField()),
                ('pickup_lng', models.FloatField()),
                ('drop_lat', models.FloatField()),
                ('drop_lng', models.FloatField()),
                ('status', models.SmallIntegerField(default=1)),
                ('cab_info', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabBookingBase.Cab')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.IntegerField()),
                ('payment_type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='payment_type_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabBookingBase.Payment'),
        ),
        migrations.AddField(
            model_name='cabbooking',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cab',
            name='cab_model_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cabBookingBase.cab_category'),
        ),
        migrations.AddField(
            model_name='cab',
            name='cab_owner_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
