# Generated by Django 2.1.1 on 2018-09-16 12:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('cabBookingBase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dob', models.DateField(max_length=8)),
                ('driver_license_number', models.CharField(max_length=15)),
                ('expiry_date', models.DateField(max_length=8)),
                ('working', models.BooleanField(default=True)),
                ('driver_booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cabBookingBase.CabBooking')),
                ('driver_name', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=1024)),
                ('destination', models.CharField(max_length=1024)),
                ('fare', models.IntegerField()),
                ('payment_booking', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cabBookingBase.CabBooking')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
