# Generated by Django 2.1.1 on 2018-09-16 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cabBookingBase', '0003_auto_20180916_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='driver',
            name='driver_booking',
            field=models.OneToOneField(blank=True, default=1, null=True, on_delete=django.db.models.deletion.PROTECT, to='cabBookingBase.CabBooking'),
        ),
    ]
